### ISSUE TITLE
How to select strings and put an 'r' in front?

### ISSUE THREAD

**Issue by mbanders** [facebookincubator/Bowler#116]
Is it possible with Bowler to select some strings (based on some filter) and have it put an `r` in front to make the string a raw string?

**Comment by thatch** [comment]
Yes it is. You can use a matcher of "STRING" and only modify the nodes you want. I have code somewhere that I wrote for 3.8 invalid escape fixing that also includes a string explode, but it will take me a few days to find it.

Was this more of a "can bowler do this" or a "please point me at example code" question?

**Comment by mbanders** [comment]
@thatch I definitely would be interested to see a code example! I have a lot of code and only some strings that I need to put an "r" in front of if the string contains certain characters.

**Comment by thatch** [comment]
Here you go, sorry this took a while.  This is a codemod I've used in production, the fun part is `bowler_invalid_escape.py:128` and the part that rewrites the string is `:169` to `:173` : https://github.com/thatch/Bowler/tree/string-editing/contrib

If you want to match `re.search('x', [anything])` you can do that with a selector.  In my case I wanted to operate on all strings and do something safe.

**Comment by mbanders** [comment]
@thatch Awesome! Thanks it worked (almost) perfectly. The one thing I had to change was the function `infer_string_type`. I just made it always `return StringType.UNICODE` because I'm running on Python3 project and none of the strings have prefixes. Python3 strings are unicode by default so, good enough and now I'm fixing strings! Thanks again.
