### ISSUE TITLE
Feature request: helper(s) to avoid syntax errors

### ISSUE THREAD

**Issue by craigds** [facebookincubator/Bowler#12]
I wrote a thing to convert `self.assertFalse(x)` to `assert not x`, etc. Trouble is, it falls over easily when the expression in the parentheses isn't valid without the parentheses:

```python
self.assertFalse(
    'a'
    'b'
)
```
My code naively converts this to

```python
assert not 'a'
    'b'
```

* I think a `parenthesize_if_necessary` helper would be really useful for this kind of situation. I imagine this bug is widespread. I tried to write one, but I'm a bit out of my depth.
* It'd be useful to have access to a function which asserts a list of nodes has no syntax errors. I realise that would vary depending on targeted python version and `__future__` imports, but perhaps something can be done? 

Thanks

**Comment by craigds** [comment]
For reference, I did manage to write `parenthesize_if_necessary`, but I think my implementation is pretty awful: https://github.com/craigds/decrapify/commit/3ae85df5c5a6f1795aaa79c899dfdeff5e732929#diff-31b11646d82d122f01238794b761b671R62

**Comment by jreese** [comment]
This is definitely something we want to have in the Bowler framework.  It should validate the final syntax tree, ensure it compiles, etc, and throw an exception if that's ever not the case.

**Comment by thatch** [comment]
I was thinking about this recently -- we can't use the py3 ast to do this (print stmt, long literals), so does fissix/lib2to3 provide a guarantee on validity on successful parse?  (Everything obviously invalid I've tried gives either ParseError or TokenError, so we've got that.)

**Comment by jreese** [comment]
fissix/lib2to3 have flags to set at parse time on whether to treat print as a function or statement, but I believe will accept py2 longs regardless.  Bowler just opts to always assume use of py3 or `from __future__ import print_function`, so always parses using the print function flag.  That said, the grammar source in lib2to3 doesn't exactly match the one-true-grammar in cypthon/Grammar, but I would generally assume that as long as it parses with lib2to3, it will be syntactically valid to cpython, as long as any transforms are generating tokens that are valid for the version of cpython being targeted (eg, don't create async/await tokens if you want the code to work on Python 3.4).

**Comment by thatch** [comment]
We have automatic validation using ast (or fissix, see pull request #78 ), closing this out.
