### ISSUE TITLE
Question: I have a working select and modifier but want it to remove the matched node, can only make the node a blank line

### ISSUE THREAD

**Issue by malsmith** [facebookincubator/Bowler#128]
I've built a selector that finds common class attributes and moves them to a superclass definition - but rather than removing the node from the matched class - I can only make the line blank, by setting by calling 
`node.children.clear() `

This also only makes an empty line not a full removal
                attrib_assignment = capture.get("attr_assignment")
                attrib_assignment.parent.children.remove(attrib_assignment)

Thanks in advance

**Comment by thatch** [comment]
Can you give a more complete example, with your bowler script, input, and output?

**Comment by thatch** [comment]
It's likely that your selector is something like `foo < attr_assignment=bar <...> >` and you need to remove the `foo` instead, which would be more like

```
attrib_assignment.parent.parent.children.remove(attrib_assignment.parent)
```

**Comment by malsmith** [comment]
Thank you for the response - I found my bug -- 
Needed to do this 
```attrib_assignment.parent.children.clear()```

The matched node also had a trailing '\n' Leaf and that piece was left behind creating the "blank line"
