### ISSUE TITLE
bowler scripts fail on files not ending with a newline

### ISSUE THREAD

**Issue by craigds** [facebookincubator/Bowler#16]
Works (output):

```bash
$ echo 'pass' > foo
$ bowler dump foo
foo
[file_input] ""
.  [simple_stmt] ""
.  .  [1] "" "pass"
.  .  [4] "" "
"
.  [0] "" ""
```

Doesn't work (no output):

```bash
$ echo -n 'pass' > foo
$ bowler dump foo
```

This seems to apply to the whole file (not finishing in a newline means no output at all for the whole file.)

**Comment by sadielbartholomew** [comment]
Hi, just to let you know I am looking into this. If I can fix it I will sign the CLA & put in a PR.
