### ISSUE TITLE
`bowler do` silently exits when IPython isn't available

### ISSUE THREAD

**Issue by jreese** [facebookincubator/Bowler#17]
Currently, when running `bowler do`, if IPython isn't available to import, Bowler will just silently exit without saying why.  

Culprit code: https://github.com/facebookincubator/Bowler/blob/master/bowler/main.py#L61

**Comment by sixninetynine** [comment]
is the intention here to bail if IPython is unavailable? Or drop into a regular (non-IPython) interpreter?
