### ISSUE TITLE
"Bowler" is nigh impossible to Google

### ISSUE THREAD

**Issue by bertjwregeer** [facebookincubator/Bowler#34]
Unfortunately `facebook bowler` does not return this project, nor is it easy to do a search for `bowler + problem` or `facebook bowler + problem` to see if anyone else is having this issue.

Cutesy names are cool and all, but there is so much noise looking for bowler that it makes it hard to use the project.

**Comment by lorencarvalho** [comment]
I searched "python bowler" and had no issues finding the official page, github page and pypi landing page

**Comment by jreese** [comment]
While the naming situation was heavily considered, it was further complicated by a few factors, including existing codemod/refactoring tools released by Facebook (eg, [codemod](/facebook/codemod), which is not Python specific), while PyPI is absolutely overflowing with generic project names that are already taken, or would be easy to get confused with.  

If you have suggestions on how to better surface this project when searching terms like "facebook bowler", we would be more than happy to consider them, or make changes to the official site or documentation.

**Comment by thatch** [comment]
I think the situation for [facebook bowler] is impossible to change, but it's the top hit for [python bowler] (to the docs, and pypi), [facebook bowler code], [facebook bowler project], and [facebook bowler refactor].  I'm fine to close this out as I don't see an action item.
