### ISSUE TITLE
AttributeError: 'Query' object has no attribute 'select_name'

### ISSUE THREAD

**Issue by SamuelMarks** [facebookincubator/Bowler#4]
[docs/api-query](https://pybowler.io/docs/api-query) [@[548fc816fab01c933bf06618670dddfeb43e9c09](https://github.com/facebookincubator/Bowler/blob/548fc816fab01c933bf06618670dddfeb43e9c09/docs/api-query.md)] references a `select_name` function, but I can't find by `grep`ping the source code.

**Comment by jreese** [comment]
Fixed by #5, must have been brain fuzz when writing all those docs! 😅
