### ISSUE TITLE
Better errors when using strings

### ISSUE THREAD

**Issue by thatch** [facebookincubator/Bowler#40]
If you use `.filter("power < any* >")` instead of `.select`, the resulting error is confusing because it just eval's string arguments.  What's the usecase for .filter taking a string?  I'd like to improve the error message if `<` is found in it as a first effort.

**Comment by jreese** [comment]
The intended use case was for potential use cases on the command line, or where simple expressions would be useful.  Eg, `query.filter("node.type == TOKEN.NAME")` or similar.  I do think it would be interesting to support further matching patterns, but given how much of that is handled by the underlying lib2to3 matching systems, I'm not sure how easy it would be to implement.

**Comment by thatch** [comment]
Let's aim for better docs then, this is hard to do in a general way.
