### ISSUE TITLE
Bowler exits with error message after successful query

### ISSUE THREAD

**Issue by jreese** [facebookincubator/Bowler#49]
## Repro

```bash
git clone https://github.com/jreese/aql
cd aql
git checkout 3565e740
bowler do  'Query().select_class("Operation").rename("Comparison").diff()'
```

## Expected result

Bowler should generate the diff and exit with success

## Actual result

Bowler generates the diff, and then outputs `Error: query failed`: https://gist.github.com/jreese/0da753bfd9a218d494bd10a7b401ce4f

Enabling debug output does not indicate any error occurred.

**Comment by jreese** [comment]
On further examination, Bowler does not actually apply the intended rename to every instance of the `Operation` name, so there might actually be an error occurring, but it's not being bubbled up correctly.

**Comment by thatch** [comment]
`BowlerTool.run()` returns an int (0 on success, 1 on error).
`bowler/main.py do()` checks against `is not None`, so it raises the exception.

Aside: the return types of `do` and `main` appear to be None but they return potentially-non-None values, is there some click magic that makes this ok?
