### ISSUE TITLE
Replace shell commands with diff-match-patch

### ISSUE THREAD

**Issue by jreese** [facebookincubator/Bowler#58]
To better support Windows (#8) and improve reliability on different environments, use of the `sh` module for the `patch` binary should be replaced with use of [diff-match-patch](https://pypi.org/project/diff-match-patch/) or a similar module.

**Comment by s0undt3ch** [comment]
I just went looking why you'd need `sh` and found this ticket.
Glad it's in the horizon to be addressed.
