### ISSUE TITLE
python2 print statements broken

### ISSUE THREAD

**Issue by ndevenish** [facebookincubator/Bowler#60]
Parsing python2 code without print functions turned on seems to be broken? The README seems to imply that this should still work (*Bowler supports modifications to code from any version of Python 2 or 3*)

Dockerfile:
```dockerfile
FROM python:3.7

RUN pip3 install git+https://github.com/facebookincubator/Bowler.git
RUN echo "print 'something'" > test.py
RUN bowler dump test.py
```
Output:
```
$ bowler dump test.py
ERROR:bowler.tool:Skipping test.py: failed to parse
```

**Comment by ndevenish** [comment]
So I've discovered that this is disabled (deliberately?) in https://github.com/facebookincubator/Bowler/blob/36d8efdb329fcb3d78ef95704f362f64d7202ed9/bowler/tool.py#L96
there's a commit singularity here so I can't see if there was a reason it was put in. Something about not requiring users to understand handling both cases?

Removing this, as in https://github.com/ndevenish/Bowler/commit/02f21581462b0084655143e6bc5364ad875b6f83,  requires a change to one of the tests to properly handle the print duality.

**Comment by jreese** [comment]
Given that this is a flag that you can pass to the refactoring system, I think it would make sense to have a similar flag (or auto-detection for each file) to properly support print statements.  The alternative would be to apply something like 2to3 or python-modernize first to upgrade to print functions, and then run Bowler, but I do think it's worth exposing as a flag on `Query` at the very least.

**Comment by ndevenish** [comment]
So with a little more research and writing converters, this actually seems to be bypassing an actual lib2to3 problem - that print functions with keyword arguments fail, unless there is a `from __future__ import print_function` statement, which obviously isn't required for >3 code.

I think a flag on `Query` would be the easiest approach, though some way of using it as a fallback for failed parsing might be more useful (e.g. running transforms over a code collection that mixes 2 and 3).

**Comment by thatch** [comment]
@jreese I would prefer to only support py3 + py2-that-uses-print_function in helpers.  The additional complexity for writing helpers (and tests) that support print statement isn't worth it IMO.

Do you have a prototype for how you'd automatically run modernize?  (And would this be hidden behind a "--upgrade-print-statement" flag?)

**Comment by jreese** [comment]
Upon further consideration with @thatch, and given the added complexity of handling divergent parse trees between the two Python grammars, I think it makes sense for us to explicitly support Python 2 only when parsed with print functions. There are too many edge cases to consider and test to support both, especially given that Python 2 is EOL this year. If you would like to use Bowler with your Python 2 code, you could either modify it locally to toggle that flag, and deal with the associated changes to the parse tree, or run your libraries through (python-modernize)[https://python-modernize.readthedocs.io/en/latest/] to update it to 2/3 compatible code first.

**Comment by ndevenish** [comment]
I mean, I'm fine with that - just you should change your README to *not* say "Bowler supports modifications to code from any version of Python 2 or 3", since print statements were only added in 2.6.

**Comment by jreese** [comment]
That's a good point, I'll update the documentation to match. Thank you.
