### ISSUE TITLE
Pybowler cannot work on Windows. Traceback: component "sh" is currently only supported on linux/osx

### ISSUE THREAD

**Issue by WinstonPoh** [facebookincubator/Bowler#8]
After installation of pybowler using pip install on windows 10, running bowler in powershell returns TB.
Steps:
1) in Python folder (typically something like C:\Python36_32), go to Scripts folder, and run ".\pip.exe install bowler.
2) run .\bowler.exe in same folder (Python36_32/Scripts)
3) TB as follows:
  ```
Traceback (most recent call last):

  File "C:\Python36\Scripts\bowler-script.py", line 11, in <module>
    load_entry_point('bowler==0.5.1', 'console_scripts', 'bowler')()

  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()

  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()

  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "c:\python36\lib\site-packages\bowler\__init__.py", line 12, in <module>
    from .tool import BowlerTool

  File "c:\python36\lib\site-packages\bowler\tool.py", line 12, in <module>
    import sh

  File "c:\python36\lib\site-packages\sh.py", line 36, in <module>
    support." % __version__)

ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```

**Comment by jreese** [comment]
Looks like `sh` explicitly does not support Windows, and the older `pbs` module has been forcibly EOL'ed by the author.  We need to find a cross-platform alternative for applying diff hunks.

**Comment by bugok** [comment]
@jreese: I didn't find a solution which I think 'nails' it, but here are a few options for you to consider:

- [patch module](https://pypi.org/project/patch/). This looks like it's what is needed, but the module looks like it's not actively maintained. 
- [Google's diff-match-patch](https://github.com/google/diff-match-patch). Looks good, but the [pip packaging](https://pypi.org/project/diff-match-patch/) doesn't seem to follow the github repo.
- Using Cygwin's patch.exe. Imagine that you'll have a module in bowler which would have an `apply_patch` function which (internally) would know about the platform its running in - and would be able to call `patch` with `subprocess` or something like that. Having Cygwin as a requirement is not ideal, but it's an option.

**Comment by sknebel** [comment]
To add to those options:

diff-match-patch might get an updated version on PyPI at some point: https://github.com/google/diff-match-patch/issues/17. 

Regarding the shell method:

* [plumbum]([https://github.com/tomerfiliba/plumbum) is another shell wrapper, per its [docs](https://plumbum.readthedocs.io/en/latest/) it supports Python 2.6-3.7 on Linux, Mac and Windows. 
* Making a single call might not be so bad through the Python APIs, esp. if maybe special-cased for Windows (using `sh` elsewhere, reducing risk of breakage there)

There's a few other sources of patch executables for Windows:

* Git for Windows both comes with a patch.exe and I think one can use `git apply` outside of repositories as a patch replacement (the latter is likely more commonly in the search path). This would have the benefit of being more likely already installed, although various GUI/IDE frontends to git install it without registering it in the search path. 

* If the busybox version of patch is sufficient, there is a one-executable [busybox for Windows](https://frippery.org/busybox/) which is thus very easy to install for users.

**Comment by jreese** [comment]
I created https://github.com/jreese/dmp as a repackaged version of diff-match-patch, which should provide the basis we need for generating and/or applying patches without depending on shelling out to `patch`.  Ultimately, shelling out is a security risk anyways, and makes the interface between client and library much more difficult to reason about or maintain.
