### ISSUE TITLE
Use parso instead of lib2to3

### ISSUE THREAD

**Issue by davidhalter** [facebookincubator/Bowler#9]
I'm just pointing this out:

If I were you, I wouldn't use lib2to3 directly. It has a lot of issues that I fixed in parso. It also has a nicer API, a refactored parser generator that you can actually understand, error recovery and a few more features that might come in handy.

**Comment by jreese** [comment]
There are a lot of benefits to using some of the existing third party libraries like parso, but the greatest benefit to using lib2to3 (or more specifically, [fissix](https://github.com/jreese/fissix)) is remaining close enough to upstream lib2to3 that we get immediate, day one support for new features of the CPython grammar.  Ideally, this will allow us to uncover more warts of lib2to3, and actively start contributing improvements back to the upstream library directly.  In the most ideal case, fissix will simply exist as a backport of lib2to3 from master, and never contain anything beyond formatting changes or extra documentation.

**Comment by davidhalter** [comment]
I never answered this anymore. While I can totally see why you would decide to do that, just know that lib2to3 is old and rotten. Nobody works on it and since Python 2 is going to retire very soon there's even less work going into it. There's a good chance that only Black's lib2to3 is going to exist in the future (5+ years). Also Guido is working on PEG parsing, so there might be a shift anyway.

Just saying that I have found and fixed a multitude of issues in lib2to3 and its tokenizer. These fixes are not upstream sometimes. blib2to3 is definitely better and doesn't have some of these issues, I do not know about how many of the fixes there have landed upstream.

BTW: You might also be interested in a Tool your co-workers wrote (if you haven't seen it): https://github.com/Instagram/LibCST/.

**Comment by jreese** [comment]
Yes, after discussions we've had with upstream at recent conferences, our position on lib2to3 has unfortunately changed. The upstream development and support we were originally expecting has evaporated, and support for 3.6+ grammar features have been mostly stuck in review.  Given this, our current plan is to migrate the Bowler concepts onto LibCST, which itself is built on top of Parso.
