### ISSUE TITLE
Callback return type

### ISSUE THREAD

**Issue by thatch** [facebookincubator/Bowler#98]
Use a more specific return type at https://github.com/facebookincubator/Bowler/blob/master/bowler/types.py#L47

Right now it's `Any`, and seems like it should be `Optional[LN]`

1. Prepare a change to do that (see [getting started docs](https://github.com/facebookincubator/Bowler/blob/master/CONTRIBUTING.md))
2. Verify that mypy is happy with it using `make lint`
3. Send a PR!

**Comment by jreese** [comment]
Yes, that makes sense to me.

**Comment by seriallazer** [comment]
I have raised a PR for this change: https://github.com/facebookincubator/Bowler/pull/134
Can someone kindly please review this, thanks!

**Comment by dragid10** [comment]
I think this issue can be closed now?
